# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=20000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

#make tty colorful
force_tty_color=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

#same but for force_tty_color
if [ -n "$force_tty_color" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	tty_color=yes
    else
	tty_color=
    fi
fi

#first so if next two if statements fail it has backup
PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '

if [ "$tty_color" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;36m\]\u\[\033[00m\] > \[\033[01;36m\]\h\[\033[00m\] > \[\033[01;36m\]\w\[\033[00m\] > \[\033[01;36m\]'
fi

if [ "$color_prompt" = yes ]; then
   PS1='${debian_chroot:+($debian_chroot)}\[\033[1;33m\][\[\033[1;36m\]\u\[\033[1;33m\]]\[\033[1;00m\] > \[\033[1;33m\][\[\033[1;36m\]\h\[\033[1;33m\]]\[\033[1;00m\] > \[\033[1;33m\][\[\033[1;36m\]\w\[\033[1;33m\]]\[\033[1;00m\] > \[\033[1;36m\]'
fi

unset color_prompt force_color_prompt tty_color force_tty_color

# If this is an xterm set the title to user >hostname > directory
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}[\u] > [\h] > [\w]\a\]$PS1"
    ;;
*)
    ;;
esac

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

neofetch
export PATH=$PATH:/home/enrorma/.local/bin
export server="insert your server ip here"
export MAKEFLAGS="-j12"

none="$(tput sgr0)"
trap 'echo -ne "${none}"' DEBUG

. $HOME/.config/aliasrc
